import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./component/Footer";
import Navbar from "./component/Navbar";
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS

import "./globals.css";
import BootstrapClient from "./BoostrapClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootstrapClient />
        <Navbar />
        <div style={{ minHeight: '80vh' }}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
